#
# 在VScode安装REST Client插件后，可使用此文件进行接口测试
#

@HOST=http://127.0.0.1:8080


###
get {{HOST}}/health

###
post {{HOST}}/api/test1
Cookie: tk=2222b22b1ce31f7cae0dcf259fceef245f60f7df21f1b1fbfc593a710f12747f

###
post {{HOST}}/api/login

{
    "username": "qf",
    "password": "qf"
}

###
post {{HOST}}/api/register

{
    "username": "qf",
    "password": "qf"
}

###
post {{HOST}}/api/QueryUser

{
    "Page": 1,
    "PageSize": 10,
    "Filters": {
        "username:ne": "11"
    }
}
###
post {{HOST}}/api/CreateUser

{
    "username":"11"
}
###
post {{HOST}}/api/UpdateUser

{
    "id":"",
    "username":"ccc"
}
###
post {{HOST}}/api/DeleteUser

{
    "id":""
}