#
# 在VScode安装REST Client插件后，可使用此文件进行接口测试
#

@HOST=http://127.0.0.1:8080


###
get {{HOST}}/health

###
post {{HOST}}/api/test1
Cookie: tk=d9ad085c281b8781cdc1bf89a5fdc0df26c488d7bf830ea81dbbf0c7e5be35b6

###
post {{HOST}}/api/test2

###
post {{HOST}}/api/register

{
    "username": "qf2",
    "password": "qf"
}

###
post {{HOST}}/api/login

{
    "username": "qf",
    "password": "qf"
}
